Changes to properly start the DB

diff --git a/.github/workflows/continuos_integration.yml b/.github/workflows/continuos_integration.yml
--- a/.github/workflows/continuos_integration.yml
+++ b/.github/workflows/continuos_integration.yml
@@ -28,20 +28,20 @@ jobs:
     container:
       image: maven:3.8.7-openjdk-18-slim
 
-    services:
-      postgres:
-        image: postgres:15  # Use the version you need
-        env:
-          POSTGRES_USER: pugliese
-          POSTGRES_PASSWORD: pugliese
-          POSTGRES_DB: authentication_management
-        ports:
-          - 5432:5432
-        options: >-
-          --health-cmd="pg_isready -U test_user"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5  
+    #services:
+    #  postgres:
+    #    image: postgres:15  # Use the version you need
+    #    env:
+    #      POSTGRES_USER: pugliese
+    #      POSTGRES_PASSWORD: pugliese
+    #      POSTGRES_DB: authentication_management
+    #    ports:
+    #      - 5432:5432
+    #    options: >-
+    #      --health-cmd="pg_isready -U test_user"
+    #      --health-interval=10s
+    #      --health-timeout=5s
+    #      --health-retries=5
 
     steps:
       - uses: actions/checkout@v4
@@ -50,6 +50,18 @@ jobs:
           distribution: 'zulu'
           java-version: 17
           cache: 'maven'
+
+      - name: Start Database
+        run: docker-compose up -d
+
+      - name: Wait for PostgreSQL
+        run: |
+          for i in {1..10}; do
+            nc -z localhost 5432 && echo "Postgres is up" && exit 0
+            echo "Waiting for Postgres..."
+            sleep 3
+          done
+          echo "Postgres did not start in time" && exit 1
 
       - name: Build and Run Tests
         run: mvn clean test
